// @ts-nocheck — auto-generated by Soroban CLI, do not edit manually
import { Buffer } from "buffer";
import { Address } from "@stellar/stellar-sdk";
import {
  AssembledTransaction,
  Client as ContractClient,
  ClientOptions as ContractClientOptions,
  MethodOptions,
  Result,
  Spec as ContractSpec,
} from "@stellar/stellar-sdk/contract";
import type {
  u32,
  i32,
  u64,
  i64,
  u128,
  i128,
  u256,
  i256,
  Option,
  Timepoint,
  Duration,
} from "@stellar/stellar-sdk/contract";
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";

if (typeof window !== "undefined") {
  //@ts-ignore Buffer exists
  window.Buffer = window.Buffer || Buffer;
}


export const networks = {
  testnet: {
    networkPassphrase: "Test SDF Network ; September 2015",
    contractId: "CARR4LRY2U4ZRBE5EDVT2CQQJ5OSMJ7MBW7USNVRWUR2DMZIT3QPSKR6",
  }
} as const


export interface Note {
  content: string;
  id: u64;
  title: string;
}

export interface Client {
  /**
   * Construct and simulate a get_notes transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  get_notes: (options?: MethodOptions) => Promise<AssembledTransaction<Array<Note>>>

  /**
   * Construct and simulate a create_note transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  create_note: ({title, content}: {title: string, content: string}, options?: MethodOptions) => Promise<AssembledTransaction<string>>

  /**
   * Construct and simulate a delete_note transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  delete_note: ({id}: {id: u64}, options?: MethodOptions) => Promise<AssembledTransaction<string>>

}
export class Client extends ContractClient {
  static async deploy<T = Client>(
    /** Options for initializing a Client as well as for calling a method, with extras specific to deploying. */
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        /** The hash of the Wasm blob, which must already be installed on-chain. */
        wasmHash: Buffer | string;
        /** Salt used to generate the contract's ID. Passed through to {@link Operation.createCustomContract}. Default: random. */
        salt?: Buffer | Uint8Array;
        /** The format used to decode `wasmHash`, if it's provided as a string. */
        format?: "hex" | "base64";
      }
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy(null, options)
  }
  constructor(public readonly options: ContractClientOptions) {
    super(
      new ContractSpec([ "AAAAAQAAAAAAAAAAAAAABE5vdGUAAAADAAAAAAAAAAdjb250ZW50AAAAABAAAAAAAAAAAmlkAAAAAAAGAAAAAAAAAAV0aXRsZQAAAAAAABA=",
        "AAAAAAAAAAAAAAAJZ2V0X25vdGVzAAAAAAAAAAAAAAEAAAPqAAAH0AAAAAROb3Rl",
        "AAAAAAAAAAAAAAALY3JlYXRlX25vdGUAAAAAAgAAAAAAAAAFdGl0bGUAAAAAAAAQAAAAAAAAAAdjb250ZW50AAAAABAAAAABAAAAEA==",
        "AAAAAAAAAAAAAAALZGVsZXRlX25vdGUAAAAAAQAAAAAAAAACaWQAAAAAAAYAAAABAAAAEA==" ]),
      options
    )
  }
  public readonly fromJSON = {
    get_notes: this.txFromJSON<Array<Note>>,
        create_note: this.txFromJSON<string>,
        delete_note: this.txFromJSON<string>
  }
}